version: '3'
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "2250:22"
      - "8080:80"
  node2:
    build: ./node
    container_name: node2
    ports:
      - "2251:22"
      - "8081:80"
